# TALLER 2: Modelo de Espacio Vectorial
Objetivo 
Comprender y aplicar el Modelo de Espacio Vectorial para el ranking de documentos basado en la similitud de contenido con una consulta dada.

Parte 1: Preparacion de Datos Creacion de la Matriz de Terminos-Documento

In [8]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Textos sobre Madrid y Dortmund
textos = {
    'Texto1': "Madrid, la capital de España, tiene una rica historia que se remonta al siglo IX. La ciudad fue fundada por los musulmanes, y su nombre proviene del árabe “Majrit” que significa “fuente de agua”. A lo largo de los siglos, Madrid se ha convertido en un centro político, económico y cultural de España.",
    'Texto2': "El Palacio Real de Madrid es una de las residencias oficiales de la familia real española, aunque ahora se usa principalmente para ceremonias de estado. Con más de 3,000 habitaciones, es el palacio real más grande de Europa Occidental y un testimonio del esplendor y la historia de España.",
    'Texto3': "El Museo del Prado es uno de los museos más famosos del mundo y un destino imprescindible para los amantes del arte que visitan Madrid. Alberga una impresionante colección de obras de Velázquez, Goya, El Greco y otros maestros europeos.",
    'Texto4': "El Parque del Retiro es el pulmón verde de Madrid. Antiguamente perteneciente a la monarquía española, este parque de 118 hectáreas ofrece un respiro de la vida urbana con sus estanques, jardines y el Palacio de Cristal.",
    'Texto5': "Madrid es famosa por su vibrante escena gastronómica que incluye desde tapas en pequeños bares hasta restaurantes de alta cocina. Platos típicos como el cocido madrileño y las patatas bravas son esenciales para cualquier visitante.",
    'Texto6': "La Gran Vía es una de las calles más famosas de Madrid, conocida por sus tiendas, teatros y arquitectura emblemática. Este bullicioso bulevar es un punto de encuentro para turistas y locales por igual.",
    'Texto7': "El Real Madrid, uno de los clubes de f´ utbol m´as famosos y exitosos del mundo, juega sus partidos en el Estadio Santiago Bernab´eu. Este estadio es una meca para los aficionados al fútbol y ofrece tours que permiten a los visitantes explorar su rica historia.",
    'Texto8': "Durante la temporada navideña, Madrid se transforma con mercados festivos, luces deslumbrantes y decoraciones. La Plaza Mayor se convierte en un enorme mercado de Navidad, donde se pueden encontrar todo tipo de regalos y delicias tradicionales.",
    'Texto9': "La Puerta del Sol es el corazón de Madrid y el lugar donde miles se reúnen cada Nochevieja para dar la bienvenida al año nuevo. Comer las doce uvas de la suerte al son de las campanadas del reloj es una tradición que todos deberían experimentar.",
    'Texto10': "Madrid Río es un parque lineal a lo largo del río Manzanares y un ejemplo perfecto de cómo la ciudad ha transformado áreas industriales en espacios verdes vibrantes. Es un lugar popular para caminar, andar en bicicleta y disfrutar de actividades al aire libre.",
    'Texto11': "Dortmund, situada en la región del Ruhr en Alemania, tiene una historia que se remonta al año 882. Originalmente una pequeña villa, Dortmund creció para convertirse en una importante ciudad industrial, especialmente conocida por su producción de acero y cerveza.",
    'Texto12': "Westfalenpark es uno de los parques urbanos más grandes de Europa y un lugar destacado para los visitantes en Dortmund. El parque es famoso por su Rosarium, que alberga una de las colecciones más extensas de rosas en el mundo, y la torre Florian, que ofrece vistas panorámicas de la ciudad.",
    'Texto13': "Inaugurado en 2015, el Museo del Fútbol Alemán ofrece una experiencia interactiva que celebra la rica historia del fútbol alemán. Ubicado en Dortmund, el museo atrae a aficionados de todo el mundo y destaca por sus exposiciones que cuentan desde los primeros días del deporte hasta los triunfos en Copas del Mundo.",
    'Texto14': "El Mercado de Navidad de Dortmund es uno de los más grandes y más visitados de Alemania. Con su gigantesco árbol de Navidad, posiblemente el más alto de los mercados navideños del país, y más de 300 puestos que venden artesanías, alimentos y bebidas tradicionales, es un evento imperdible durante la temporada festiva.",
    'Texto15': "El U-Tower, una antigua cervecería reconvertida, es ahora un centro dinámico de arte y creatividad. Alberga el Museo Ostwall, espacios de exposiciones y estudios de artistas, y es un símbolo de la transformación cultural de Dortmund.",
    'Texto16': "Borussia Dortmund es uno de los clubes de fútbol más populares y exitosos de Alemania. El equipo juega sus partidos en casa en el Signal Iduna Park, conocido por su increíble atmósfera y el famoso “Muro Amarillo”, la tribuna sur que alberga a 25,000 aficionados apasionados.",
    'Texto17': "Dortmund tiene una larga tradición cervecera, y la visita a una de sus muchas cervecerías es una parada obligatoria. Las cervecerías ofrecen tours que incluyen degustaciones de cervezas locales como Dortmunder Export, una lager que es un orgullo de la ciudad.",
    'Texto18': "La iglesia de San Reinold es el edificio más antiguo de Dortmund, datando del siglo XIII. Es un punto de referencia histórico importante y ofrece a los visitantes una mirada al pasado medieval de la ciudad.",
    'Texto19': "Dortmund fue un objetivo significativo durante los bombardeos de la Segunda Guerra Mundial debido a su industria pesada. Hoy en día, varios monumentos y museos ofrecen reflexiones sobre este período y sus efectos en la ciudad.",
    'Texto20': "El Zoológico de Dortmund es un lugar excelente para familias y amantes de la naturaleza. Con más de 1,500 animales y un enfoque especial en la conservación de especies amenazadas, el zoológico proporciona una experiencia educativa y entretenida.",
}

# Categorias
categorias = ["Turismo", "Historia", "Guerra", "Fútbol", "Realeza", "Gastronomía", "Arte y Cultura", "Naturaleza y Medio Ambiente", "Arquitectura", "Comercio", "Festividades", "Transporte", "Educación", "Tecnología", "Deportes (otros)", "Religión", "Ocio y Entretenimiento", "Salud y Bienestar", "Industria", "Urbanismo"]


# Generar palabras relacionadas para todas las categorías

palabras_relacionadas = {
    "Turismo": ["excursión", "aventura", "viaje", "destino", "tour operador", "guía turístico", "atractivo turístico", "alojamiento", "turismo rural", "turismo de aventura"],
    "Historia": ["antigüedad", "prehistoria", "Edad Antigua", "Edad Media", "Edad Moderna", "Edad Contemporánea", "revolución", "independencia", "revolución industrial", "Revolución Francesa"],
    "Guerra": ["conflicto armado", "batalla", "guerrero", "ejército", "estrategia militar", "armamento", "tregua", "violencia", "paz", "conquista"],
    "Fútbol": ["jugador", "equipo", "entrenador", "árbitro", "estadio", "campeonato", "liga", "copa", "gol", "afición", "Madrid", "Dortmund"],
    "Realeza": ["rey", "reina", "príncipe", "princesa", "monarquía", "corona", "trono", "dinastía", "palacio real", "protocolo"],
    "Gastronomía": ["plato típico", "chef", "receta", "degustación", "restaurante", "comida callejera", "gastronomía internacional", "vinoteca", "cocina gourmet", "cata de vinos"],
    "Arte y Cultura": ["museo", "exposición", "obra de arte", "artista", "movimiento artístico", "patrimonio cultural", "ballet", "teatro", "literatura", "cultura popular"],
    "Naturaleza y Medio Ambiente": ["parque nacional", "reserva natural", "biodiversidad", "ecosistema", "flora", "fauna", "conservación ambiental", "reciclaje", "contaminación", "desarrollo sostenible"],
    "Arquitectura": ["edificio", "monumento", "rascacielos", "arco", "columna", "fachada", "arquitectura moderna", "arquitectura histórica", "diseño urbano", "patrimonio arquitectónico"],
    "Comercio": ["mercado", "comercio internacional", "negocio", "comerciante", "producto", "servicio", "economía", "exportación", "importación", "tarifa arancelaria"],
    "Festividades": ["celebración", "festividad religiosa", "carnaval", "feria", "desfile", "ritual", "tradición", "fiesta popular", "evento cultural", "día festivo"],
    "Transporte": ["vehículo", "transporte público", "infraestructura de transporte", "aeropuerto", "estación de tren", "puerto", "tráfico", "conductor", "peatón", "movilidad urbana"],
    "Educación": ["escuela", "universidad", "maestro", "alumno", "aprendizaje", "educación a distancia", "formación profesional", "aula", "examen", "programa educativo"],
    "Tecnología": ["innovación tecnológica", "dispositivo móvil", "red social", "aplicación móvil", "inteligencia artificial", "realidad virtual", "tecnología wearable", "software", "hardware", "ciberseguridad"],
    "Deportes (otros)": ["baloncesto", "tenis", "atletismo", "natación", "ciclismo", "gimnasia", "boxeo", "rugby", "voleibol", "hockey sobre hielo"],
    "Religión": ["templo", "iglesia", "mezquita", "sinagoga", "oración", "creencia", "sacerdote", "festividad religiosa", "peregrinación", "fe"],
    "Ocio y Entretenimiento": ["cine", "teatro", "concierto", "parque de atracciones", "zoológico", "videojuego", "lectura", "pasatiempo", "karaoke", "baile"],
    "Salud y Bienestar": ["salud mental", "nutrición", "ejercicio físico", "medicina preventiva", "bienestar emocional", "terapia", "meditación", "vida saludable", "sueño reparador", "spa"],
    "Industria": ["fábrica", "producción industrial", "manufactura", "sector industrial", "innovación tecnológica", "proceso productivo", "trabajador", "maquinaria", "cadena de producción", "industria automotriz"],
    "Urbanismo": ["ciudad", "planificación urbana", "desarrollo urbano", "espacio público", "movilidad urbana", "arquitectura urbana", "sostenibilidad urbana", "diseño urbano", "zonificación urbana", "infraestructura urbana"]
}




# Crear un diccionario para almacenar los conteos de categorías por texto
data = {categoria: [] for categoria in categorias}

# Contar cuántas veces aparece cada categoría en cada texto
for texto in textos.values():
    for categoria in categorias:
        palabras_categoria = palabras_relacionadas[categoria]
        count = sum(texto.lower().count(palabra) for palabra in palabras_categoria)
        data[categoria].append(count)

# Crear un DataFrame a partir del diccionario
df = pd.DataFrame(data, index=textos.keys())

# Mostrar la matriz de términos-documento
print(df)




         Turismo  Historia  Guerra  Fútbol  Realeza  Gastronomía  \
Texto1         0         0       0       0        0            0   
Texto2         0         0       0       0        2            0   
Texto3         1         0       0       0        0            0   
Texto4         0         0       0       0        1            0   
Texto5         0         0       0       0        0            1   
Texto6         0         0       0       0        0            0   
Texto7         0         0       0       2        0            0   
Texto8         0         0       0       0        0            0   
Texto9         0         0       0       0        0            0   
Texto10        0         0       0       0        0            0   
Texto11        0         0       0       0        0            0   
Texto12        0         0       0       0        0            0   
Texto13        0         0       0       1        0            0   
Texto14        0         0       0       0      

In [9]:
# Crear la matriz término-documento utilizando CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(textos)
print(X)

  (0, 0)	1
  (1, 11)	1
  (2, 13)	1
  (3, 14)	1
  (4, 15)	1
  (5, 16)	1
  (6, 17)	1
  (7, 18)	1
  (8, 19)	1
  (9, 1)	1
  (10, 2)	1
  (11, 3)	1
  (12, 4)	1
  (13, 5)	1
  (14, 6)	1
  (15, 7)	1
  (16, 8)	1
  (17, 9)	1
  (18, 10)	1
  (19, 12)	1


In [10]:

# Calcular la similitud coseno entre los textos
similarity_matrix = cosine_similarity(X)

# Imprimir la matriz de similitud coseno
print("Matriz de Similitud Coseno:")
print(similarity_matrix)

Matriz de Similitud Coseno:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0